### PR TITLE
Laravel 5.4

### PR DESCRIPTION
**Pull request by maddhatter**
Add Laravel 5.4 support.

I didn't extensively test this, but I did do basic testing - creating a new sluggable record works.

### CODE REVIEW

**Comment by cviebrock** [comment]
Cool!  I noticed that the Travis tests all passed, but it looks like it's using 5.3.9 still.  Did you run the unit tests locally?

**Comment by maddhatter** [comment]
Ah it's probably using that since 5.4 hasn't been tagged as stable yet. I updated the minimum-stability of my local `composer.json` to `dev` so that it would pull in 5.4.x-dev, and it's passing:
```
PHPUnit 5.7.6-18-gc1551dc by Sebastian Bergmann and contributors.

.......................III.....................                   47 / 47 (100%)

Time: 3.32 seconds, Memory: 18.75MB

OK, but incomplete, skipped, or risky tests!
Tests: 47, Assertions: 114, Incomplete: 3.
```

**Comment by bingvanmoorsel** [comment]
+1 for maddhatter!

**Comment by cviebrock** [comment]
Cheers!

**Pull request merged**
