### PR TITLE
update for Laravel 5.1 compatibility

### PR DESCRIPTION
**Pull request by UnrulyNatives**
guess you need another branch. at least temporarily - to support both versions L5 and L5.1

### CODE REVIEW

**Comment by Keoghan** [comment]
Can we do this to support both at once? E.g.

```
php

use Illuminate\Support\Collection;

...

protected function getExistingSlugs($slug)
	{
		$config = $this->getSluggableConfig();
		$save_to         = $config['save_to'];
		$include_trashed = $config['include_trashed'];

		$instance = new static;

		$query = $instance->where( $save_to, 'LIKE', $slug.'%' );

		// include trashed models if required
		if ( $include_trashed && $this->usesSoftDeleting() )
		{
			$query = $query->withTrashed();
		}

		// get a list of all matching slugs
		$list = $query->lists($save_to, $this->getKeyName());

		return $list instanceof Collection ? $list->all() : $list;
	}

```

**Comment by cviebrock** [comment]
I prefer @Keoghan's approach.  Did you PR that?

**Comment by Keoghan** [comment]
Hi - yes, sorry, I should have done separately, but it's included in the Issue 141 PR.

**Comment by cviebrock** [comment]
Solved by #148

**Pull request closed without merging**
