### PR TITLE
Fixes #203, PostgreSQL returns ModelNotFoundException instead of Quer…

### LINKED ISSUE #203: QueryException instead of ModelNotFoundException using PostgreSQL
Hi, 
When using PostgreSQL with the following in RouteServiceProvider:

```
       $router->bind('tests', function($db)
        {
            return \App\Test::findBySlugOrIdOrFail($db);
        });
```
You get the following error:
```
QueryException in Connection.php line 651:
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "eino-nienow-foobar-ab-aliquam" (SQL: select * from "tests" where "tests"."deleted_at" is null and "tests"."id" = eino-nienow-foobar-ab-aliquam limit 1)
```
It does fail, but not as expected as it does when using MySQL, because there it returns a ```ModelNotFoundException```.

### PR DESCRIPTION
**Pull request by Jaspur**
…yException

### CODE REVIEW

**Comment by cviebrock** [comment]
So PostgreSQL doesn't cast this automatically when querying by ID? I'm primarily a MySQL guy, so in not sure. But, if this is the case, do you not need to do this *everywhere* you use Eloquent's `Model::find($id)` ... since I'd assume the route parameter isn't automatically cast. 

Also, there is the odd case where someone may set up their models to not use an integer primary key (UUIDs for example), in which case this would be a breaking change. 

Just want to get some clarification before I merge this. 

Thanks!

**Comment by Jaspur** [comment]
@cviebrock I added some more info in the issue I opened for this: #203

```
QueryException in Connection.php line 651:
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "eino-nienow-foobar-ab-aliquam" (SQL: select * from "tests" where "tests"."deleted_at" is null and "tests"."id" = eino-nienow-foobar-ab-aliquam limit 1)
```

As you can see it returns ```invalid input syntax for integer```, so it expects an integer when there is not Slug where it matches to when doing ```findBySlugOrIdOrFail()```

But regarding your question, no you don't have to do it everywhere when using ```Model::find($id)```. Just for some reason your code does it, and what I pushed is a fix for that.

**Comment by Jaspur** [comment]
?

**Comment by cviebrock** [comment]
Thanks!

**Pull request merged**
