### PR TITLE
Allow slugify bool false and falsy values 0 & '0'

### PR DESCRIPTION
**Pull request by arturock**

### CODE REVIEW

**Comment by cviebrock** [comment]
In short, this is just making it so that only `null` source values don't produce slugs?

Just wondering how to handle source values that are booleans.

**Comment by arturock** [comment]
I didn't want to really mess w/ the code so I only added a check to allow passing `0` and `'0'` adding `is_numeric` to [the condition that checks if there's a value to slugify](https://github.com/cviebrock/eloquent-sluggable/pull/351/commits/e2d6e3092256905543457b73e325db094b1117d0#diff-91da43484863003579be4cb543205ae4R83) so any other value will be processed as it used to be. `true` will pass and `false` wont. As bools were not part of the use case I didn't check them

**Comment by arturock** [comment]
Just added some local tests to check bools out :) `true` as source becomes `1` and `false` keeps null as slug as expected. I  can gladly add those tests to the PR if you want to.

**Comment by cviebrock** [comment]
Yeah, that would be good, I think.  The check can then get simplified to:
```php
if ($source !== null) {
```
which is also nice. ;)

If people are using booleans as the source, I think that's their problem.

**Comment by arturock** [comment]
I initally thought about that but then an empty string will generate an empty slug. A `null` value could be better option as slug without data is clearly broken, but maybe we are fixing stuff that corresponds to the dev that uses the package. What do you think?

**Comment by arturock** [comment]
It was a little strange that `true` becames `1` but `false` `null` so made an update for a consistent behavior. Let me know what you think!

**Comment by cviebrock** [comment]
I like.  Thanks you!

**Comment by joecohens** [comment]
👍

**Pull request merged**
