### PR TITLE
Auto router model

### PR DESCRIPTION
**Pull request by Keoghan**
Hi

This is my first pull-request (ever), hopefully it is of some use and you'll consider it for your project which I found immensely useful picking up Laravel.

The key aim here was to make the slugs easy to use from the go with minimal additional setup. (And still be optional). I've added a couple of helper functions, a revised model() method in a new SluggableRouter with a simple Service Provider which replaces the Laravel Standard Router. I've also attempted some basic documentation.

Thanks,

Keoghan

### CODE REVIEW

**Comment by Keoghan** [comment]
Oh - sorry added some tests too!

**Comment by cviebrock** [comment]
This looks pretty darn good.  Thank you!

**Comment by Keoghan** [comment]
Thanks - glad I could contribute something back!

**Comment by Keoghan** [comment]
Hi, 

I've found that the changes we merged are not functioning properly. I believe the issue comes down to the kernel, and it holding it's own version of the Router throughout it's life.

I had thought the `rebinding()` of the new Router into the service container in the SluggableRoutingServiceProvider had resolved the problem, but some further testing suggests not.

I have a modified version in which I now `bind()` the router, but for it to work, it requires a change to the kernel, whereby it retrieves the router again before dispatch. 

I've not managed to think of a better way around it, but think perhaps it's not a simple enough solution for that functionality to remain in your main repo? 

I can prepare a pull either way, removing functionality, or making the changes and documenting what to do to get it to work - which would you prefer?

**Comment by cviebrock** [comment]
Hrmm ... that's too bad, because it's a pretty cool "feature".

I think it'd be safer to remove the functionality for now and document it, and then revisit later on.

Thanks for the effort on this!

**Pull request merged**
