### PR TITLE
php 8.0 support

### PR DESCRIPTION
**Pull request by cbl**
This pr adds support for the new major php version 8.0

### CODE REVIEW

**Comment by cviebrock** [comment]
This looks good to me ... except that Travis doesn't appear to have a stable PHP8 image yet.  I'm going to wait until then to merge this and create a new version.

**Comment by cbl** [comment]
Could you please merge and tag this already I am depending on this package in a lot of projects that I cant wait to Update to php 8. I have tested this and It works with php8. 

I would also offer to create a pr which is moving tests from Travis to GitHub actions.

**Comment by cviebrock** [comment]
I’d be up for the move to GitHub actions. Travis doesn’t have a PHP 8.0 env yet, and it’s becoming super slow waiting for any tests to run.

**Comment by fulopattila122** [comment]
I'm using `nightly` in travis config instead of `8.0` and it perfectly does the job (until Travis adds plain 8.0 support)

See how I'm doing it: https://github.com/artkonekt/enum/blob/3.1.0/.travis.yml#L6
And the result: https://travis-ci.com/github/artkonekt/enum/builds/205062668

If travis builds are slow, migrate over from travis-ci.org to travis-ci.com.
I did it for 20+ repos, and it's unfortunately not very straightforward.
Here's a step by step guide that can significantly shorten the process: https://news.ycombinator.com/item?id=24922775

Ah, and I'm also depending on your package... 😅

:bow:

**Comment by cviebrock** [comment]
Thanks!  I'll push version 8.0.2 of the package shortly.

**Pull request merged**
