### PR TITLE
applied StyleCI style fixes

### PR DESCRIPTION
**Pull request by kkiernan**
Applies the [recommended preset](https://styleci.readme.io/v1.0/docs/presets#recommended) from StyleCI to clean up some stylistic stuff.

### CODE REVIEW

**Comment by cviebrock** [comment]
While I am a big fan of consistent code styling, I'm not 100% sold on this.  There are a handful of "definitive PHP code styles" out there it seems, including PSR-2, and several ways of enforcing them.

StyleCI seems pretty cool, but I'd rather it start out with some kind of configuration file that's checked into the project, rather than just fixes per merge request.  Something like what http://editorconfig.org/ provides.

And, no matter what anyone else says, tabs are always better than spaces for indenting IMHO.  ;)

**Comment by kkiernan** [comment]
That sounds like a good way to go. Thought I'd send the pr over anyway :) I agree with the tabs! I've been trying out spaces recently for PSR-2's sake. Feels strange...

**Comment by cviebrock** [comment]
If there was something that could be included in the project that:

1. was fairly standard (i.e. PSR-X),
2. could be tweaked (e.g. tabs instead of spaces),
3. could enforce the code-style in the major editors (i.e. Sublime Text, PHPStorm, Zend, Atom), and
4. wasn't super crazy to implement

I'd be all over that. ;)

**Comment by cviebrock** [comment]
FWIW, I bit the bullet and changed the code to PSR-2.  Feel free to look through and let me know if I missed anything (I mostly used PHPStorm's auto code-styling to convert everything).

**Comment by kkiernan** [comment]
Oh nice! I'm excited to take a look.

**Pull request closed without merging**
