### PR TITLE
[WIP] Remember Previously Used Slugs

### PR DESCRIPTION
**Pull request by colindecarlo**
Referencing [Issue #328](https://github.com/cviebrock/eloquent-sluggable/issues/328), this is just a first pass (and incomplete) at attempting to remember previous slugs for slugged entities. 

I hope to use this PR more so as an RFC on the approach I took and to test whether this is a viable feature.

This is what I think the package will need to complete this feature

- [ ] an option in the config to turn this feature on or off (possibly a set of options to configure the behaviour of the feature)
- [ ] a new database table to store previously used slugs
- [ ] a model listener for the `slugging` event to capture the existing slug and move it to the `old_slugs` table
 - [ ] a middleware to intercept requests asking for old slugs and redirecting to the current slug
 - [ ] some rules regarding what to do if slugs collide in the `old_slugs` table
 - [ ] updates to the Service Provider to publish the new migration
 - [ ] documentation

Currently, all I've implemented is a rough draft of the middleware which redirects requests to old slugs. Honestly, I'm not crazy that this is implemented as a "before" middleware, in that, old slugs are taking precedence over current slugs but in order for this to work as an "after" middleware, I'd have to hook into the ExceptionHandler somehow and I'm not sure if you can do that or not (I'll have to check). 

Let me know what you think.

Thank you for helping to make this package better!

Please make sure you've read [CONTRIBUTING.md](https://github.com/cviebrock/eloquent-sluggable/blob/master/CONTRIBUTING.md) 
before submitting your pull request, and that you have:

- [x] provided a rationale for your change (I try not to add features that are going to have a limited user-base)
- [x] used the [PSR-2 Coding Standard](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md)
- [x] added tests
- [ ] documented any change in behaviour (e.g. updated the `README.md`, etc.)
- [ ] only submitted one pull request per feature

**Thank you!**

### CODE REVIEW

**Comment by cviebrock** [comment]
I like the idea and approach.  However, I think this package needs a major rewrite to solve some other issues, and part of that is making me think that slugs should reside in their own table and be a polymorphic relation to user Models.  This could simplify the "old slug - new slug" issue, because everything is in one place.

So, I'm going to thank you for your PR -- and I'll probably go through it to steal ideas! -- but I'm not going to merge it at this point.

**Comment by colindecarlo** [comment]
Ya for sure, the last thing I wanted to happen would be the PR being merged as it is. If you'd like some help or want to collaborate on this new iteration of the package I'm happy to help out. Moving all the slugs into one table makes sense and does address this problem nicely.

**Comment by cyrildewit** [comment]
@cviebrock Keep in mind that if you store slugs in a seperated table with a polymorphic relation, it will be required to have two queries to retrieve for example a post.

Is a simple `old_slugs` or `slug_history` table not enough? When the `SlugService` creates a new slug it can do a simple check. If it's available: add slug to the model and save it in the history. Using model events, we can also remove slugs from the history if wanted.

**Comment by shirshak55** [comment]
I think doing by data centric way is better isn't it ?

**Comment by cviebrock** [comment]
Closing due to no response or activity in a while.  Feel free to re-open or comment if you are still having issues or rework the PR with the latest package version.

**Pull request closed without merging**
