### PR TITLE
Laravel 10.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l10-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/cviebrock/eloquent-sluggable/pull/589/commits/7fe0e6880ce7132ff44a666f6b3271f71294ea7e?w=1) for Laravel 10. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/eloquent-sluggable.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "cviebrock/eloquent-sluggable": "dev-l10-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by pxpm** [comment]
Hey @cviebrock I've given this a test on my side, everything seems to be working fine as far as I've tested.

Tests are failing because https://github.com/orchestral/database didn't add support for Laravel10 yet, but I was able to run the tests by removing `orchestral/database` from the `require-dev` dependencies in `composer.json`.

image

It seems safe to merge either removing `orchestral/database` from dev-dependencies, or wait for them to add support.
Let me know if I can help with something else.

Cheers

**Comment by cviebrock** [comment]
Hi @pxpm ... I'll take a look at this shortly.  But isn't orchestral/database required for complete testing (haven't looked at that side of things in a while).

**Comment by pxpm** [comment]
> Hi @pxpm ... I'll take a look at this shortly. But isn't orchestral/database required for complete testing (haven't looked at that side of things in a while).

I haven't gone deep into the tests, I just removed that dependency and ran `--testdox`, everything came back green, so I assume everything is working as expected without that dev-dependency. 

Maybe some latest changes in testbench package don't require to specify that package anymore ? 

Cheers

**Comment by rickgoemans** [comment]
If I check the new 10.x branch of Laravel I also see that phpunit is updated to version to `^10.0`, shouldn't this be reflected in this PR?

https://github.com/laravel/laravel/blob/10.x/composer.json#L20

**Comment by jasonmccreary** [comment]
It's a `dev` requirement and therefore not required directly when installing this package. That would be a requirement for your application.

**Comment by rickgoemans** [comment]
Oops, you're right, my mistake. 

Any ideas on when this package will PR will be tested/merged?

**Comment by jasonmccreary** [comment]
Nope. I just send in this automation to help maintainers and early adopters. You can test it yourself by following the comments above. Up to the maintainer to merge.

**Comment by pxpm** [comment]
@cviebrock just to bring to your attention the following comment about the `orchestral/database` dependency: https://github.com/calebporzio/sushi/pull/109#pullrequestreview-1243131338

Cheers

**Comment by cviebrock** [comment]
Version 10.0.0 has been released

**Pull request closed without merging**
