### PR TITLE
Added Laravel 10.* support

### PR DESCRIPTION
**Pull request by scrumble-niels**
I have tested this with "minimum-stability" on "dev" since Laravel 10 hasn't been released yet at the time of contributing this. Thank you for developing this package.

### CODE REVIEW

**Comment by cviebrock** [comment]
A few comments:
- I don't think `nunomaduro/collision` is required, is it?
- I'll need to update the test matrix as well
I'll probably just combine this PR with #589 from laravel-shift and put out a new version shortly.

**Comment by scrumble-niels** [comment]
> A few comments:
> 
> * I don't think `nunomaduro/collision` is required, is it?
> * I'll need to update the test matrix as well
>   I'll probably just combine this PR with [Laravel 10.x Compatibility #589](https://github.com/cviebrock/eloquent-sluggable/pull/589) from laravel-shift and put out a new version shortly.

I have used `php vendor/bin/testbench package:test` to test the package locally. This requires `nunomaduro/collision`.

**Comment by thyseus** [comment]
Laravel 10 is released :partying_face: 

any chances to get this merged and packaged into a `10.0` soon ?

Allowing phpunit 10 like

```
"phpunit/phpunit": "^9.4|^10.0"
```

would also be great.

Thanks a lot !!

**Comment by jamesautodude** [comment]
I tried using Laravel 10 and composer gives me these errors:

```
- Root composer.json requires cviebrock/eloquent-sluggable ^9.0 -> satisfiable by cviebrock/eloquent-sluggable[9.0.0].

- Only one of these can be installed: illuminate/config[v9.0.0, ..., v9.52.0], laravel/framework[v10.0.0]. laravel/framework replaces illuminate/config and thus cannot coexist with it.

- cviebrock/eloquent-sluggable 9.0.0 requires illuminate/config ^9.0 -> satisfiable by illuminate/config[v9.0.0, ..., v9.52.0].

- Root composer.json requires laravel/framework ^10.0 -> satisfiable by laravel/framework[v10.0.0].
```

**Comment by wahyulingu** [comment]
Im waiting to someone fix it wkwkwkwk

**Comment by jamesautodude** [comment]
> Im waiting to someone fix it wkwkwkwk

Me too lol. It doesn't sound hopeful though as prior pull request for upgrade was ignored....

**Comment by wahyulingu** [comment]
> > Im waiting to someone fix it wkwkwkwk
> 
> Me too lol. It doesn't sound hopeful though as prior pull request for upgrade was ignored....

is the problem with nunomaduro?

**Comment by jamesautodude** [comment]
> > > Im waiting to someone fix it wkwkwkwk
> > 
> > 
> > Me too lol. It doesn't sound hopeful though as prior pull request for upgrade was ignored....
> 
> is the problem with nunomaduro?

No the problem is with the author, cviebrock

You can see his responses in this pull request and he never merged it:
https://github.com/cviebrock/eloquent-sluggable/pull/589

**Comment by wahyulingu** [comment]
> > > > Im waiting to someone fix it wkwkwkwk
> > > 
> > > 
> > > Me too lol. It doesn't sound hopeful though as prior pull request for upgrade was ignored....
> > 
> > 
> > is the problem with nunomaduro?
> 
> No the problem is with the author of eloquent-sluggable, cviebrock
> 
> You can see his responses in this pull request and he never merged it: #589

wkwkwk

**Comment by cviebrock** [comment]
Version 10.0.0 has been released.

**Pull request closed without merging**
