### PR TITLE
A way of adding custum rules to Cocur\SlugifySlugify instance

### PR DESCRIPTION
**Pull request by muratsplat**
https://github.com/cviebrock/eloquent-sluggable/issues/164

### CODE REVIEW

**Comment by muratsplat** [comment]
some prive and protected methods are changed to public and protected methods...

I hope my commits is acceptable for @cviebrock :

**Comment by cviebrock** [comment]
Can you fix up the merge conflicts?

**Comment by muratsplat** [comment]
ok

**Comment by cviebrock** [comment]
Actually, I took a longer look at this.

My slug usage is pretty typical, and generally limited to English words, so I don't have the same perspective as you do.  However, it seems to me that this PR adds a fair amount of code for a fairly small set of use cases.

I think, rather than add all this configuration into the eloquent-sluggable package -- which is really there to configure the concur/sluggable package -- there is an easier solution: I can break out a method that instantiates the `Slugify()` class.  If you have specific needs for that class (i.e. adding custom rules, etc.), then you can just override that class in your models, and do whatever you want there.

I'll take care of this shortly, and show you what I mean.

**Comment by muratsplat** [comment]
Yes .. I liked your idea.. It is hard to set Slugify Instance via config file..

**Comment by cviebrock** [comment]
Pushed: https://github.com/cviebrock/eloquent-sluggable/commit/b5374dc793627e0d0b7dfd48c19236e8e67b8e12

**Comment by muratsplat** [comment]
That is it... The simple is more better :+1:

**Pull request closed without merging**
