### PR TITLE
Fix issue #141.

### PR DESCRIPTION
**Pull request by Keoghan**
Hi - tried to fix up this issue by changing the findBy* methods from being scope methods to static methods.

Also added in tweak for Laravel 5.1.

### CODE REVIEW

**Comment by cviebrock** [comment]
Do you mind fixing this up to be able to automatically merge?

**Comment by Keoghan** [comment]
Just working that out :)

**Comment by rajivseelam** [comment]
Any comments on when this might be merged? 

Thanks.

**Comment by cviebrock** [comment]
How about "now".  Is "now" good for you? :stuck_out_tongue_winking_eye:

**Comment by rajivseelam** [comment]
"Now" is apparently too early for me :stuck_out_tongue_winking_eye: 

Thanks a lot for your amazing support :100:

**Pull request merged**
